---
- hosts: all
  gather_facts: no
  tasks:
    - name: .gitconfig
      file: src={{ playbook_dir }}/files/gitconfig dest=~/.gitconfig state=link force=yes
    - name: .gitignore_global
      file: src={{ playbook_dir }}/files/gitignore_global dest=~/.gitignore_global state=link force=yes
    - name: .bash_aliases
      file: src={{ playbook_dir }}/files/bash_aliases dest=~/.bash_aliases state=link force=yes
    - name: prepare vim and nvim config directories
      file: path={{ item }}/autoload state=directory recurse=Yes
      with_items:
        - ~/.vim/
        - ~/.config/nvim
    - name: .config/nvim/init.vim
      file: src={{ playbook_dir }}/files/vimrc dest=~/.config/nvim/init.vim state=link force=true
    - name: .vimrc
      file: src={{ playbook_dir }}/files/vimrc dest=~/.vimrc state=link force=true
