---
- hosts: all
  sudo: true
  tasks:
    - name: update apt cache
      apt: update_cache=yes
    - name: apt-get install
      apt: name={{ item }} state=latest
      with_items:
        - tree
        - cmake
        - ctags
        - git
        - subversion
        - mercurial
        - build-essential
        - automake
        - autoconf
        - autotools-dev
        - llvm
        - clang-3.5
        - lldb-3.5
        - gdb
        - flex
        - bison
        - python-pip
        - python3-pip
        - python-dev
        - python-setuptools
        - python-virtualenv
        - default-jre
        - default-jdk
        - libedit-dev
        - erlang-base
    - name: Set clang-3.5 as alias for clang
      file: src=/usr/bin/clang-3.5 dest=/usr/bin/clang state=link
    - name: Set clang-3.5++ as alias for clang++
      file: src=/usr/bin/clang++-3.5 dest=/usr/bin/clang++ state=link
    - name: Set lldb-3.5 as alias for lldb
      file: src=/usr/bin/lldb-3.5 dest=/usr/bin/lldb state=link
