---
- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: update apt cache
      apt: update_cache=yes
    - name: apt-get install
      apt: name={{ item }} state=latest
      with_items:
        # Vim
        - vim-gnome
        # Python
        - python-setuptools
        - python-virtualenv
        # Python 2
        - python2.7
        - python2.7-dbg
        - python2.7-dev
        - python-pip
        # Python 3
        - python3-all
        - python3-all-dbg
        - python3-all-dev
        - python3-pip
        # Tmux
        - tmux
        # Git
        - git
        - git-flow
        # Version control
        - subversion
        - mercurial
        # Java
        - openjdk-8-jre
        - openjdk-8-jdk
        - maven
        - ant
        - ant-contrib
        - gradle
        # KVM
        - qemu-kvm
        # C/C++
        - build-essential
        - automake
        - autoconf
        - autotools-dev
        - gcc
        - g++
        - gdb
        - libc6-dev
        - clang
        - llvm
        - lldb
        - cmake
        # Rust
        - rust-doc
        - rust-gdb
        - rust-lldb
        - rustc
        # Clojure
        - clojure1.6
        # Erlang
        - erlang-base
        # Ruby
        - ruby
        # NodeJS
        - nodejs
        - npm
        # GPG
        - gnupg
        # TeX
        - texlive-full
        # Other
        - emacs
        - tree
        - man-db
        - sudo
        - xclip
        - ctags
        - ack-grep
        - flex
        - bison
