---
- hosts: all
  gather_facts: no
  tasks:
    - name: .gitconfig
      file: src={{ playbook_dir }}/files/gitconfig dest=~/.gitconfig state=link force=yes
    - name: .gitignore_global
      file: src={{ playbook_dir }}/files/gitignore_global dest=~/.gitignore_global state=link force=yes
    - name: .bash_aliases
      file: src={{ playbook_dir }}/files/bash_aliases dest=~/.bash_aliases state=link force=yes
    - name: .inputrc
      file: src={{ playbook_dir }}/files/inputrc dest=~/.inputrc state=link force=yes
    - name: prepare vim and nvim config directories
      file: path={{ item }}/autoload state=directory recurse=Yes
      with_items:
        - ~/.vim/
        - ~/.config/nvim
    - name: install vim-plug
      get_url:
        dest: "{{ item }}/autoload/plug.vim"
        url: 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
      with_items:
        - ~/.vim/
        - ~/.config/nvim/
    - name: .config/nvim/init.vim
      file: src={{ playbook_dir }}/files/vimrc dest=~/.config/nvim/init.vim state=link force=true
    - name: .vimrc
      file: src={{ playbook_dir }}/files/vimrc dest=~/.vimrc state=link force=true
    - name: .emacs
      file: src={{ playbook_dir }}/files/emacs dest=~/.emacs state=link force=true
    - name: .tmux.conf
      file: src={{ playbook_dir }}/files/tmux.conf dest=~/.tmux.conf state=link force=true
