---
- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Install apt-transport-https
      apt: name=apt-transport-https state=latest
    - name: Add gpg key for weechat
      shell: apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 11E9DE8848F2B65222AA75B8D1820DB22A11534E
      become: yes
    - name: Add PPA for golang
      apt_repository: repo='ppa:ubuntu-lxc/lxd-stable' state=present
    - name: Add PPA for Neovim
      apt_repository: repo='ppa:neovim-ppa/unstable' state=present
    - name: Add repo for Weechat
      apt_repository: 
        repo: deb https://weechat.org/ubuntu yakkety main
        state: present
    - name: update apt cache
      apt: update_cache=yes
    - name: apt-get install
      apt: name={{ item }} state=latest
      with_items:
        # Vim
        - vim-gnome
        - neovim
        # Python
        - python-setuptools
        - python-virtualenv
        # Python 2
        - python2.7
        - python2.7-dbg
        - python2.7-dev
        - python-pip
        # Python 3
        - python3-all
        - python3-all-dbg
        - python3-all-dev
        - python3-pip
        - python3-setuptools
        # Tmux
        - tmux
        # Git
        - git
        - git-flow
        # Version control
        - subversion
        - mercurial
        - fossil
        # Java
        - openjdk-8-jre
        - openjdk-8-jdk
        - maven
        - ant
        - ant-contrib
        - gradle
        # KVM
        - qemu-kvm
        # C/C++
        - build-essential
        - automake
        - autoconf
        - autotools-dev
        - gcc
        - g++
        - gdb
        - lcov
        - valgrind
        - libc6-dev
        - clang
        - llvm
        - lldb
        - cmake
        - libreadline-dev
        - libgdbm-dev
        - libssl-dev
        - libz3-dev
        - libre2-dev
        - libgraphicsmagick1-dev
        - libtiff5-dev
        - libfreetype6-dev
        - libjasper-dev
        - libjpeg-dev
        - libpng-dev
        - libbz2-dev
        - libgomp1
        - libwebp-dev
        - liblzma-dev
        - libncurses5-dev
        - libaspell-dev
        - libfuse-dev
        - libdlib-dev
        - libgtest-dev
        - libboost-all-dev
        - libiomp-dev
        - gnulib
        - libglib2.0-dev
        - mesa-common-dev
        - libsdl1.2-dev
        - freeglut3-dev
        - libxft-dev
        - libxmu-headers
        - libxmu-dev
        - libevent-dev
        - libxft2
        - libtool
        - libtool-bin
        - libapr1
        - libapr1-dbg
        - libapr1-dev
        - libaprutil1
        - libaprutil1-dev
        # Tcl
        - tcl
        - tcl-dev
        - tcl-doc
        # Lua
        - lua-any
        # Rust
        - rust-doc
        - rust-gdb
        - rust-lldb
        - rustc
        # Clojure
        - clojure1.6
        # Erlang
        - erlang-base
        # Ruby
        - ruby
        # NodeJS
        - nodejs
        - npm
        # GPG
        - gnupg
        # TeX
        - texlive-full
        # SciPy
        - python-numpy
        - python-scipy
        - python-matplotlib
        - ipython 
        - ipython-notebook
        - python-pandas
        - python-sympy
        - python-nose
        # OCaml
        - ocaml
        - opam
        # Archives
        - unrar-free
        - p7zip-full
        - cabextract
        # Mail
        - msmtp
        - mutt
        - git-email
        - offlineimap
        # Other
        - emacs
        - mc
        - tree
        - man-db
        - sudo
        - xclip
        - ctags
        - ack-grep
        - flex
        - bison
        - doxygen
        - python-sphinx
        - telnet
        - dh-make
        - rpm
        - xsltproc
        - uuid-runtime
        - sup-mail
        - fontconfig
        - asciidoc
        # Weechat
        - libgcrypt20-dev
        - weechat-core
        - weechat-curses
        - weechat-plugins
        - weechat
        # Go
        - golang
        # C Sharp
        - mono-complete
        - mono-devel
    - name: Use ld.gold instead ld.bfd
      shell: update-alternatives --install "/usr/bin/ld" "ld" "/usr/bin/ld.gold" 20 && update-alternatives --install "/usr/bin/ld" "ld" "/usr/bin/ld.bfd" 10 && update-alternatives --config ld
    - name: pip install
      pip: name={{ item }} executable=pip  state=latest
      with_items:
        - jupyter
        - requests
        - pyyaml
        - Jinja2
    - name: pip3 install
      pip: name={{ item }} executable=pip3  state=latest
      with_items:
        - requests
        - pyyaml
        - Jinja2
        - cookiecutter
    - name: Set zsh as default shell
      user:
        name: user
        shell: /bin/zsh
