---
- hosts: all
  sudo: true
  tasks:
    - name: update apt cache
      apt: update_cache=yes
    - name: apt-get install
      apt: name={{ item }} state=latest
      with_items:
        - tree
        - cmake
        - ctags
        - git
        - subversion
        - mercurial
        - build-essential
        - automake
        - autoconf
        - autotools-dev
        - gdb
        - flex
        - bison
        - python-pip
        - python3-pip
        - python-dev
        - python-setuptools
        - python-virtualenv
        - default-jre
        - default-jdk
        - libedit-dev
