alias vi='nvim'
alias vim='nvim'
alias l='ls -alF'
alias ll='ls -l'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'

git() {
  case $1 in
    tag)
      shift
      command git tag -s "$@"
      ;;
    commit)
      shift
      command git commit --signoff "$@"
      ;;
    log)
      shift
      command git log --show-signature "$@"
      ;;
    *)
      command git "$@";;
  esac
}


